### ISSUE TITLE
Misleading property in job spec

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry-incubator/datadog-firehose-nozzle#11]
The property `properties.uaa.username` and `properties.uaa.password` is misleading as in reality it is `properties.uaa.client` and `properties.uaa.client_secret`.

Would you mind renaming the property in next final release?

**Comment by apoydence** [comment]
We [updated](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/commit/97171a347270fd1f10f893010fd9976de7f511a3) the property names.
