### ISSUE TITLE
datadogclient should set "Content-type: application/json" header while POST

### ISSUE THREAD

**Issue by syslxg** [cloudfoundry-incubator/datadog-firehose-nozzle#12]
we are writing an datadog proxy using sinatra. The proxy receives metrics from datadog-firehose-nozzle , proccesses them, then send to datadog.com. Because the datadogclient package in this repo does not send "Content-type: application/json" header while emitting metrics, our proxy fails because Rack tries to parse the huge json in body as params. We add `req.Header.Set("Content-type", "application/json")` at https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/blob/master/datadogclient/datadog_client.go#L117, and that solved our issue.

**Comment by wfernandes** [comment]
@syslxg Thanks for bringing this up. We'll try and prioritize it as soon as possible. 
If you'd like to contribute we encourage you to create a PR for this issue as well.

**Comment by iplay88keys** [comment]
This was fixed here: https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/commit/a954f5ba91f41936823720797b540a89a1ed5b26
