### ISSUE TITLE
How does slowConsumerAlert work with latest Loggregator?

### ISSUE THREAD

**Issue by robertjsullivan** [cloudfoundry-incubator/datadog-firehose-nozzle#16]
https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle#slowconsumeralert

We are using the nozzle to connect to the latest loggregator, and we are not seeing the slowConsumerAlert. Can you confirm that the two rules ( the TruncatingBuffer.DroppedMessages metric and the `1008` on disconnect) are still accurate?

**Comment by apoydence** [comment]
Loggregator will close a "slow" connection and expect the client to reconnect. I have [updated](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/blob/4e2e419be28ef11cdb12b57156bc4edc559c3bd6/README.md#slowconsumeralert) the README.md to reflect this.

**Comment by ahevenor** [comment]
cc @irabinovitch
