### ISSUE TITLE
Getting error while running main.go file

### ISSUE THREAD

**Issue by vineetbadola** [cloudfoundry-incubator/datadog-firehose-nozzle#3]
Hi

I am trying to setup the datadog nozzle to push the metrics from firehose to Datadog
As per the configuration we only need to change UAA prperties in cloudfoundry manifest and then change the config.json file.
But when i am trying to run the main.go file with below command

go run main.go -config config/datadog-firehose-nozzle.json

I am getting below error
# command-line-arguments
./main.go:49: syntax error: unexpected range, expecting {
./main.go:55: syntax error: unexpected }

Kindly help me on the same

**Comment by wfernandes** [comment]
Hey @vineetbadola,

I wasn't able to reproduce your output. Below is my output.
```
go run main.go -config config/datadog-firehose-nozzle.json
2016/02/03 22:33:41 Targeting datadog API URL: https://app.datadoghq.com/api/v1/series
2016/02/03 22:33:41 Error getting oauth token: Received a status code 401 Unauthorized. Please check your username and password.
exit status 1
```
All I did was:

1. cd $GOPATH
1. `go get github.com/cloudfoundry-incubator/datadog-firehose-nozzle`
1. `go run main.go -config config/datadog-firehose-nozzle.json`

From what you have shown, it does seem you have a syntax error in `main.go` which probably means the file was modified.

Here are some tips to get this to work:
- Make sure your GOPATH is set correctly
- Make sure you have the latest [noaa](https://github.com/cloudfoundry/noaa) library in your GOPATH.
- Apart from the username and password, please add your datadog api key and make sure json is valid.

Please let us know if you continue to see this issue.

Thanks.

**Comment by wfernandes** [comment]
@vineetbadola Also check your version of go. We looked at the line on which you are getting your syntax error and it could be that the `for range` syntax might not be supported in earlier versions of golang.

Thanks.

**Comment by daverc1-pivotal** [comment]
This has been resolved, problem was an older version of go. @vineetbadola please mark as closed.
