### ISSUE TITLE
NOZZLE_METRIC_PREFIX is written once instead NOZZLE_METRICPREFIX in the README

### ISSUE THREAD

**Issue by ebornier-pivotal** [cloudfoundry-incubator/datadog-firehose-nozzle#4]
NOZZLE_METRIC_PREFIX is written once instead NOZZLE_METRICPREFIX in the README

**Comment by Jim-Campbell** [comment]
Thanks! We're on it

On Tue, Mar 8, 2016 at 7:02 AM, cf-gitbot <notifications@github.com> wrote:

> We have created an issue in Pivotal Tracker to manage this. You can view
> the current status of your issue at:
> https://www.pivotaltracker.com/story/show/115244495.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/issues/4#issuecomment-193795367>
> .
>



-- 
Jim Campbell | Product Manager | Cloud Foundry | Pivotal.io | 303.618.0963

**Comment by jasonkeene** [comment]
Thanks for reporting this! I just pushed a commit to update that command. Feel free to open PRs for stuff like this in the future.

Closed by f77dacc35110e2767f2129bd4369185c4a11f87c
