### ISSUE TITLE
Deprecated NOAA library

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry-incubator/datadog-firehose-nozzle#5]
After building I'm now getting a warning for using a deprecated noaa consumer.  Can this project switch to the new library?

```
2016/04/18 09:21:35 Starting DataDog Firehose Nozzle...
2016/04/18 09:21:35 You are using a deprecated noaa consumer (noaa.Consumer).  Please switch to 'github.com/cloudfoundry/noaa/consumer'.Consumer at your earliest convenience.
2016/04/18 09:21:50 Posting 835 metrics
```

**Comment by wfernandes** [comment]
@mjseid We recently changed NOAA's implementation. We will be moving to the new consumer package soon.

**Comment by wfernandes** [comment]
Fixed with [this PR](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/pull/6)
