### ISSUE TITLE
Get container metrics from the firehose

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry-incubator/datadog-firehose-nozzle#9]
Does this nozzle gather app container metrics?  It appears that container metrics are accounted for in the client test programs but I don't see anything that handles container metrics in the actual datadog_client and I don't appear to be getting any container metrics from the nozzle.

**Comment by Jim-Campbell** [comment]
We have written [a spike](https://www.pivotaltracker.com/story/show/121458609) to investigate the costs and benefits of doing this. You can track the progress in [the Loggregator backlog](https://www.pivotaltracker.com/n/projects/993188).

**Comment by wfernandes** [comment]
@mjseid Sorry for the late response but at the moment this not a priority for the Loggregator team and we will not be pursuing this feature in the short term. 

However, we do encourage pull-requests and would be willing to review updates to the nozzle. My best guess would be a flag that turns this feature on-off (defaulting to off) for backward compatibility and throughput reasons.
